version: '3.4'
services:

  #
  # Infrastructure dependencies
  #

  master_graph:
    tty: false
    image: dgraph/standalone:v1.2.2
    ports:
      - "8000:8000"
      - "8080:8080"
      - "9080:9080"

  engagement_graph:
    tty: false
    image: dgraph/standalone:v1.2.2
    ports:
      - "8001:8000"
      - "8081:8080"
      - "9081:9080"

  sqs:
    image: localstack/localstack
    environment:
      - SERVICES=sqs:9324
      - HOSTNAME_EXTERNAL=sqs.us-east-1.amazonaws.com
    ports:
      - "9324:9324"

  s3:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"

  dynamodb:
    image: amazon/dynamodb-local

  #
  # Rust services
  #

  grapl-sysmon-subgraph-generator:
    build:
      context: ./rust
      target: grapl-sysmon-subgraph-generator
    command: ./sysmon-subgraph-generator
    tty: false
    environment:
      - BUCKET_PREFIX="local-grapl"
      - IS_LOCAL="True"
    links:
      - s3:minio
      - sqs:sqs.us-east-1.amazonaws.com
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1
    depends_on:
      - s3
      - sqs
      - graph_provision

  grapl-node-identifier:
    build:
      context: ./rust
      target: grapl-node-identifier
    command: ./node-identifier
    environment:
      - BUCKET_PREFIX="local-grapl"
      - IS_LOCAL="True"
    tty: false
    links:
      - s3:minio
      - dynamodb:dynamo
      - sqs:sqs.us-east-1.amazonaws.com
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1
    depends_on:
      - s3
      - dynamodb
      - sqs
      - dynamodb_provision

  grapl-node-identifier-retry-handler:
    build:
      context: ./rust
      target: grapl-node-identifier-retry-handler
    command: ./node-identifier-retry-handler
    environment:
      - BUCKET_PREFIX="local-grapl"
      - IS_LOCAL="True"
    tty: false
    links:
      - s3:minio
      - dynamodb:dynamo
      - sqs:sqs.us-east-1.amazonaws.com
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1
    depends_on:
      - s3
      - dynamodb
      - sqs
      - dynamodb_provision

  grapl-graph-merger:
    build:
      context: ./rust
      target: grapl-graph-merger
    command: ./graph-merger
    environment:
      - BUCKET_PREFIX="local-grapl"
      - IS_LOCAL="True"
    tty: false
    links:
      - s3:minio
      - sqs:sqs.us-east-1.amazonaws.com
      - master_graph
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1
    depends_on:
      - s3
      - sqs
      - graph_provision
      - master_graph

  grapl-analyzer-dispatcher:
    build:
      context: ./rust
      target: grapl-analyzer-dispatcher
    command: ./analyzer-dispatcher
    environment:
      - BUCKET_PREFIX="local-grapl"
      - IS_LOCAL="True"
    tty: false
    links:
      - s3:minio
      - sqs:sqs.us-east-1.amazonaws.com
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1
    depends_on:
      - s3
      - sqs

  #
  # Non-rust services
  #

  grapl-analyzer-executor:
    build:
      context: ./analyzer_executor
      target: grapl-analyzer-executor
    command: python3 /src/analyzer-executor.py
    environment:
      - IS_LOCAL="True"
      - GRPC_ENABLE_FORK_SUPPORT=1
      - MG_ALPHAS=master_graph
      - IS_RETRY="False"
      - BUCKET_PREFIX=local-grapl
    links:
      - s3:minio
      - sqs:sqs.us-east-1.amazonaws.com
      - master_graph:master_graph
    tty: true
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1

  grapl-engagement-creator:
    build:
      context: ./engagement-creator
      target: grapl-engagement-creator
    command: python3 /src/engagement-creator.py
    environment:
      - IS_LOCAL="True"
      - BUCKET_PREFIX=local-grapl
    tty: true
    links:
      - s3:minio
      - sqs:sqs.us-east-1.amazonaws.com
      - engagement_graph:engagement_graph
      - master_graph:master_graph
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1

  grapl_engagement_edge:
    build:
      context: ./engagement_ux/engagement_edge
      target: grapl-engagement-edge
    command: chalice local --no-autoreload --host=0.0.0.0 --port=8900
    ports:
      - "8900:8900"
    environment:
      - IS_LOCAL="True"
    tty: true
    links:
      - engagement_graph:engagement_graph

  grapl_engagement_view:
    build:
      context: ./engagement_ux/engagement_view
      target: grapl-engagement-view
    environment:
      - PORT=1234
    ports:
      - 1234:1234

  grapl-notebook:
    image: grapl/grapl-notebook
    links:
      - engagement_graph:engagement_graph
      - master_graph:master_graph
    ports:
      - 8888:8888

  #
  # Provision local datastores
  #

  graph_provision:
    build:
      context: ./engagement_ux/engagement_edge
      target: grapl-engagement-edge
    volumes:
      - ./local_grapl/:/var/run/target/
    command: python /var/run/target/grapl_provision.py
    tty: false
    links:
      - engagement_graph
      - master_graph
      - s3:minio
      - sqs:sqs.us-east-1.amazonaws.com
    extra_hosts:
      - sqs:127.0.0.1
      - amazonaws:127.0.0.1
      - minio:127.0.0.1

  dynamodb_provision:
    build:
      context: ./engagement_ux/engagement_edge
      target: grapl-engagement-edge
    volumes:
      - ./local_grapl/local_dynamodb:/var/run/target/
    command: python /var/run/target/provision_local_identity_table.py
    tty: false
    links:
      - dynamodb:dynamodb
    extra_hosts:
      - amazonaws:127.0.0.1
