[package]
name = "grapl-config"
version = "0.1.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"

[dependencies]
sqs-lambda = "0.20.1"
rusoto_core = {version="0.43.0-beta.1", default_features = false, features=["rustls"]}
